application: jkimuli
version: 1
runtime: python27
api_version: 1

threadsafe: false

handlers:

- url: /static
  static_dir: static
  
- url: /.*
  script: main.py
  
builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
  

  